---
- name: Play to patch only CentOS systems
  hosts: all
  become: true

  tasks: 
  - name: Patch CentOS systems
    yum:
      name: httpd
      state: latest
    when: ansible_facts['distribution'] == "CentOS"


