---
- name: Play to patch only Fedora systems
  hosts: all
  become: true

  tasks: 
  - name: Patch Fedora systems
    yum:
      name: httpd
      state: latest
    when: (ansible_facts['distribution'] == "Fedora" and ansible_facts['distribution_major_version'] == "35")


