---
- name: Play to test for hosts file in directory output
  hosts: localhost

  tasks: 
    - name: Gather directory listing from local system
      ansible.builtin.shell: "ls -l"
      register: shellresult

    - name: Alert if we find a hosts file
      ansible.builtin.debug:
        msg: "Found hosts file!"
      when: '"hosts" in shellresult.stdout'

