---
- name: Play to patch only Fedora systems
  hosts: all
  become: true

  tasks: 
  - name: Patch Fedora systems
    ansible.builtin.dnf:
      name: httpd
      state: latest
    when: ansible_facts['distribution'] == "Fedora"


