---
- name: Install Apache
  hosts: web01.example.org
  gather_facts: no
  become: yes

  tasks:
    - name: Install Apache package
      ansible.builtin.apt:
        name: apache2
        state: latest

    - name: Open firewall for Apache
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - "http"
        - "https"

    - name: Restart and enable the service
      ansible.builtin.service:
        name: apache2
        state: restarted
        enabled: yes
