---
- name: Simple loop demo play
  hosts: web01.example.org

  tasks:
    - name: Echo a value from the loop
      ansible.builtin.command: echo "{{ item }}"
      loop:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
      when: item|int > 3
      register: loopresult

    - name: Print the results from the loop
      ansible.builtin.debug:
        var: loopresult
