---
- hosts: frontends
  remote_user: james

  tasks:
  - name: simple connection test
    ansible.builtin.ping:
    remote_user: james

  - name: run a simple command
    ansible.builtin.shell: /bin/ls -al /nonexistent
    ignore_errors: True
