---
- name: Play 1 - configure the frontend servers
  hosts: frontends
  become: yes

  tasks:
  - name: Install the Apache package
    ansible.builtin.apt:
      name: apache2
      state: latest
  - name: Start the Apache server
    ansible.builtin.service:
      name: apache2
      state: started

- name: Play 2 - configure the application servers
  hosts: apps
  become: true 

  tasks:
  - name: Install Tomcat
    ansible.builtin.apt:
      name: tomcat9
      state: latest
  - name: Start the Tomcat server
    ansible.builtin.service:
      name: tomcat9
      state: started
