---
- name: Play to demonstrate the run_once directive
  hosts: frontends
  serial: 5

  tasks:
    - name: Upgrade database schema
      debug:
        msg: Upgrading database schema...
      run_once: true
