---
- hosts: localhost
  tasks:
  - name: Ensure key pair is present
    amazon.aws.ec2_key:
      name: fale
      key_material: "{{ lookup('file', '~/.ssh/fale.pub') }}"
  - name: Gather information of the EC2 VPC net in eu-west-1
    amazon.aws.ec2_vpc_net_info:
      region: eu-west-1
    register: aws_simple_net
  - name: Gather information of the EC2 VPC subnet in eu-west-1
    amazon.aws.ec2_vpc_subnet_info:
      region: eu-west-1
      filters:
        vpc-id: '{{ aws_simple_net.vpcs.0.id }}'
    register: aws_simple_subnet
  - name: Ensure wssg Security Group is present
    amazon.aws.ec2_security_group:
      name: wssg
      description: Web Security Group
      region: eu-west-1
      vpc_id: '{{ aws_simple_net.vpcs.0.id }}'
      rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
    register: aws_simple_wssg
  - name: Setup instance
    amazon.aws.ec2_instance:
      assign_public_ip: true
      image: ami-3548444c
      region: eu-west-1
      exact_count: 1
      key_name: fale
      count_tag:
        Name: ws01.ansible2cookbook.com
      instance_tags:
        Name: ws01.ansible2cookbook.com
      instance_type: t2.micro
      group_id: '{{ aws_simple_wssg.group_id }}'
      vpc_subnet_id: '{{ aws_simple_subnet.subnets.0.id }}'
      volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 10
        delete_on_termination: True
