---
- hosts: localhost
  tasks:
  - name: Get information from K8s
    kubernetes.core.k8s_info:
      api_version: v1
      kind: Namespace
      register: ns
  - name: Print info
    ansible.builtin.debug:
      var: ns
