---
- hosts: localhost
  tasks:
  - name: Start a container with a command
    containers.podman.podman_container:
      name: test-container
      image: alpine
      command:
      - echo
      - "Hello, World!"
