---
- hosts: localhost
  tasks:
  - name: Start a container with a command
    community.docker.docker_container:
      name: test-container
      image: alpine
      command:
      - echo
      - "Hello, World!"
