---
- name: My first Ansible playbook
  hosts: all
  become: yes

  tasks:
  - name: Update the latest of an Apache Web Server
    yum: 
      name: httpd
      state: latest
    notify:
      - Restart an Apache Web Server

  handlers:
  - name: Restart an Apache Web Server
    service: 
      name: httpd
      state: restarted

