---
- name: Simple play to demonstrate a return value
  hosts: localhost

  tasks:
    - name: Perform a simple module based task
      ansible.builtin.ping:
      register: pingresult

    - name: Display the result
      ansible.builtin.debug:
        var: pingresult
