---
- name: Play to demonstrate our custom filter
  hosts: frontends
  gather_facts: false
  vars:
    statement: "Puppet is an excellent automation tool!"
 
  tasks:
    - name: make a statement
      debug:
        msg: "{{ statement | improve_automation }}"
