--- 
ungrouped: 
  hosts: 
    target1.example.org: 
      ansible_host: 192.168.81.142 
      ansible_port: 3333 
    target2.example.org: 
      ansible_port: 3333 
      ansible_user: james 
    target3.example.org: 
      ansible_host: 192.168.81.143 
      ansible_port: 5555 
